// ============================================================
// 日本語の先生 — Veri Dosyası
// Kana tabloları, kanji listesi, kelimeler ve okuma metinleri
// ============================================================

// ---------- KANA (Hiragana + Katakana eşleşmeli) ----------
// h: hiragana, k: katakana, r: romaji
export const KANA_GROUPS = [
  {
    name: "Temel Sesler (Gojūon)",
    rows: [
      [{h:"あ",k:"ア",r:"a"},{h:"い",k:"イ",r:"i"},{h:"う",k:"ウ",r:"u"},{h:"え",k:"エ",r:"e"},{h:"お",k:"オ",r:"o"}],
      [{h:"か",k:"カ",r:"ka"},{h:"き",k:"キ",r:"ki"},{h:"く",k:"ク",r:"ku"},{h:"け",k:"ケ",r:"ke"},{h:"こ",k:"コ",r:"ko"}],
      [{h:"さ",k:"サ",r:"sa"},{h:"し",k:"シ",r:"shi"},{h:"す",k:"ス",r:"su"},{h:"せ",k:"セ",r:"se"},{h:"そ",k:"ソ",r:"so"}],
      [{h:"た",k:"タ",r:"ta"},{h:"ち",k:"チ",r:"chi"},{h:"つ",k:"ツ",r:"tsu"},{h:"て",k:"テ",r:"te"},{h:"と",k:"ト",r:"to"}],
      [{h:"な",k:"ナ",r:"na"},{h:"に",k:"ニ",r:"ni"},{h:"ぬ",k:"ヌ",r:"nu"},{h:"ね",k:"ネ",r:"ne"},{h:"の",k:"ノ",r:"no"}],
      [{h:"は",k:"ハ",r:"ha"},{h:"ひ",k:"ヒ",r:"hi"},{h:"ふ",k:"フ",r:"fu"},{h:"へ",k:"ヘ",r:"he"},{h:"ほ",k:"ホ",r:"ho"}],
      [{h:"ま",k:"マ",r:"ma"},{h:"み",k:"ミ",r:"mi"},{h:"む",k:"ム",r:"mu"},{h:"め",k:"メ",r:"me"},{h:"も",k:"モ",r:"mo"}],
      [{h:"や",k:"ヤ",r:"ya"},null,{h:"ゆ",k:"ユ",r:"yu"},null,{h:"よ",k:"ヨ",r:"yo"}],
      [{h:"ら",k:"ラ",r:"ra"},{h:"り",k:"リ",r:"ri"},{h:"る",k:"ル",r:"ru"},{h:"れ",k:"レ",r:"re"},{h:"ろ",k:"ロ",r:"ro"}],
      [{h:"わ",k:"ワ",r:"wa"},null,null,null,{h:"を",k:"ヲ",r:"wo"}],
      [{h:"ん",k:"ン",r:"n"},null,null,null,null],
    ],
  },
  {
    name: "Dakuten ﾞ / Handakuten ﾟ (Yumuşak / Patlamalı Sesler)",
    rows: [
      [{h:"が",k:"ガ",r:"ga"},{h:"ぎ",k:"ギ",r:"gi"},{h:"ぐ",k:"グ",r:"gu"},{h:"げ",k:"ゲ",r:"ge"},{h:"ご",k:"ゴ",r:"go"}],
      [{h:"ざ",k:"ザ",r:"za"},{h:"じ",k:"ジ",r:"ji"},{h:"ず",k:"ズ",r:"zu"},{h:"ぜ",k:"ゼ",r:"ze"},{h:"ぞ",k:"ゾ",r:"zo"}],
      [{h:"だ",k:"ダ",r:"da"},{h:"ぢ",k:"ヂ",r:"ji"},{h:"づ",k:"ヅ",r:"zu"},{h:"で",k:"デ",r:"de"},{h:"ど",k:"ド",r:"do"}],
      [{h:"ば",k:"バ",r:"ba"},{h:"び",k:"ビ",r:"bi"},{h:"ぶ",k:"ブ",r:"bu"},{h:"べ",k:"ベ",r:"be"},{h:"ぼ",k:"ボ",r:"bo"}],
      [{h:"ぱ",k:"パ",r:"pa"},{h:"ぴ",k:"ピ",r:"pi"},{h:"ぷ",k:"プ",r:"pu"},{h:"ぺ",k:"ペ",r:"pe"},{h:"ぽ",k:"ポ",r:"po"}],
    ],
  },
  {
    name: "Birleşik Sesler (Yōon)",
    rows: [
      [{h:"きゃ",k:"キャ",r:"kya"},null,{h:"きゅ",k:"キュ",r:"kyu"},null,{h:"きょ",k:"キョ",r:"kyo"}],
      [{h:"しゃ",k:"シャ",r:"sha"},null,{h:"しゅ",k:"シュ",r:"shu"},null,{h:"しょ",k:"ショ",r:"sho"}],
      [{h:"ちゃ",k:"チャ",r:"cha"},null,{h:"ちゅ",k:"チュ",r:"chu"},null,{h:"ちょ",k:"チョ",r:"cho"}],
      [{h:"にゃ",k:"ニャ",r:"nya"},null,{h:"にゅ",k:"ニュ",r:"nyu"},null,{h:"にょ",k:"ニョ",r:"nyo"}],
      [{h:"ひゃ",k:"ヒャ",r:"hya"},null,{h:"ひゅ",k:"ヒュ",r:"hyu"},null,{h:"ひょ",k:"ヒョ",r:"hyo"}],
      [{h:"みゃ",k:"ミャ",r:"mya"},null,{h:"みゅ",k:"ミュ",r:"myu"},null,{h:"みょ",k:"ミョ",r:"myo"}],
      [{h:"りゃ",k:"リャ",r:"rya"},null,{h:"りゅ",k:"リュ",r:"ryu"},null,{h:"りょ",k:"リョ",r:"ryo"}],
      [{h:"ぎゃ",k:"ギャ",r:"gya"},null,{h:"ぎゅ",k:"ギュ",r:"gyu"},null,{h:"ぎょ",k:"ギョ",r:"gyo"}],
      [{h:"じゃ",k:"ジャ",r:"ja"},null,{h:"じゅ",k:"ジュ",r:"ju"},null,{h:"じょ",k:"ジョ",r:"jo"}],
      [{h:"びゃ",k:"ビャ",r:"bya"},null,{h:"びゅ",k:"ビュ",r:"byu"},null,{h:"びょ",k:"ビョ",r:"byo"}],
      [{h:"ぴゃ",k:"ピャ",r:"pya"},null,{h:"ぴゅ",k:"ピュ",r:"pyu"},null,{h:"ぴょ",k:"ピョ",r:"pyo"}],
    ],
  },
];

// ---------- KELİMELER ----------
// w: yazılışı (kanji varsa kanjili), kana: tam kana okunuşu, m: Türkçe anlamı
export const WORDS = [
  // --- Hiragana ile başlayanlar ---
  {w:"朝", kana:"あさ", m:"sabah"},
  {w:"雨", kana:"あめ", m:"yağmur"},
  {w:"秋", kana:"あき", m:"sonbahar"},
  {w:"犬", kana:"いぬ", m:"köpek"},
  {w:"家", kana:"いえ", m:"ev"},
  {w:"一", kana:"いち", m:"bir (sayı)"},
  {w:"海", kana:"うみ", m:"deniz"},
  {w:"歌", kana:"うた", m:"şarkı"},
  {w:"駅", kana:"えき", m:"istasyon"},
  {w:"映画", kana:"えいが", m:"film"},
  {w:"お茶", kana:"おちゃ", m:"çay"},
  {w:"お金", kana:"おかね", m:"para"},
  {w:"傘", kana:"かさ", m:"şemsiye"},
  {w:"川", kana:"かわ", m:"nehir"},
  {w:"家族", kana:"かぞく", m:"aile"},
  {w:"木", kana:"き", m:"ağaç"},
  {w:"昨日", kana:"きのう", m:"dün"},
  {w:"北", kana:"きた", m:"kuzey"},
  {w:"今日", kana:"きょう", m:"bugün"},
  {w:"教室", kana:"きょうしつ", m:"sınıf, derslik"},
  {w:"靴", kana:"くつ", m:"ayakkabı"},
  {w:"雲", kana:"くも", m:"bulut"},
  {w:"今朝", kana:"けさ", m:"bu sabah"},
  {w:"結婚", kana:"けっこん", m:"evlilik"},
  {w:"子供", kana:"こども", m:"çocuk"},
  {w:"言葉", kana:"ことば", m:"kelime, dil"},
  {w:"魚", kana:"さかな", m:"balık"},
  {w:"桜", kana:"さくら", m:"kiraz çiçeği (sakura)"},
  {w:"新聞", kana:"しんぶん", m:"gazete"},
  {w:"白", kana:"しろ", m:"beyaz"},
  {w:"写真", kana:"しゃしん", m:"fotoğraf"},
  {w:"宿題", kana:"しゅくだい", m:"ödev"},
  {w:"寿司", kana:"すし", m:"suşi"},
  {w:"水曜日", kana:"すいようび", m:"çarşamba"},
  {w:"先生", kana:"せんせい", m:"öğretmen"},
  {w:"世界", kana:"せかい", m:"dünya"},
  {w:"空", kana:"そら", m:"gökyüzü"},
  {w:"外", kana:"そと", m:"dışarı"},
  {w:"卵", kana:"たまご", m:"yumurta"},
  {w:"食べ物", kana:"たべもの", m:"yiyecek"},
  {w:"地図", kana:"ちず", m:"harita"},
  {w:"父", kana:"ちち", m:"baba(m)"},
  {w:"茶色", kana:"ちゃいろ", m:"kahverengi"},
  {w:"月", kana:"つき", m:"ay (gökteki)"},
  {w:"机", kana:"つくえ", m:"masa, sıra"},
  {w:"手", kana:"て", m:"el"},
  {w:"手紙", kana:"てがみ", m:"mektup"},
  {w:"鳥", kana:"とり", m:"kuş"},
  {w:"友達", kana:"ともだち", m:"arkadaş"},
  {w:"夏", kana:"なつ", m:"yaz"},
  {w:"名前", kana:"なまえ", m:"isim"},
  {w:"肉", kana:"にく", m:"et"},
  {w:"庭", kana:"にわ", m:"bahçe"},
  {w:"布", kana:"ぬの", m:"kumaş"},
  {w:"沼", kana:"ぬま", m:"bataklık, gölcük"},
  {w:"猫", kana:"ねこ", m:"kedi"},
  {w:"値段", kana:"ねだん", m:"fiyat"},
  {w:"飲み物", kana:"のみもの", m:"içecek"},
  {w:"海苔", kana:"のり", m:"deniz yosunu (nori)"},
  {w:"花", kana:"はな", m:"çiçek"},
  {w:"春", kana:"はる", m:"ilkbahar"},
  {w:"人", kana:"ひと", m:"insan, kişi"},
  {w:"昼", kana:"ひる", m:"öğlen, gündüz"},
  {w:"百", kana:"ひゃく", m:"yüz (100)"},
  {w:"冬", kana:"ふゆ", m:"kış"},
  {w:"船", kana:"ふね", m:"gemi"},
  {w:"部屋", kana:"へや", m:"oda"},
  {w:"蛇", kana:"へび", m:"yılan"},
  {w:"本", kana:"ほん", m:"kitap"},
  {w:"星", kana:"ほし", m:"yıldız"},
  {w:"窓", kana:"まど", m:"pencere"},
  {w:"町", kana:"まち", m:"şehir, kasaba"},
  {w:"水", kana:"みず", m:"su"},
  {w:"耳", kana:"みみ", m:"kulak"},
  {w:"虫", kana:"むし", m:"böcek"},
  {w:"村", kana:"むら", m:"köy"},
  {w:"目", kana:"め", m:"göz"},
  {w:"眼鏡", kana:"めがね", m:"gözlük"},
  {w:"森", kana:"もり", m:"orman"},
  {w:"桃", kana:"もも", m:"şeftali"},
  {w:"山", kana:"やま", m:"dağ"},
  {w:"野菜", kana:"やさい", m:"sebze"},
  {w:"雪", kana:"ゆき", m:"kar"},
  {w:"夢", kana:"ゆめ", m:"rüya, hayal"},
  {w:"夜", kana:"よる", m:"gece"},
  {w:"洋服", kana:"ようふく", m:"kıyafet"},
  {w:"来年", kana:"らいねん", m:"gelecek yıl"},
  {w:"楽", kana:"らく", m:"rahat, kolay"},
  {w:"林檎", kana:"りんご", m:"elma"},
  {w:"旅行", kana:"りょこう", m:"seyahat"},
  {w:"留学", kana:"りゅうがく", m:"yurtdışında eğitim"},
  {w:"留守", kana:"るす", m:"evde olmama"},
  {w:"歴史", kana:"れきし", m:"tarih (geçmiş)"},
  {w:"零", kana:"れい", m:"sıfır"},
  {w:"六", kana:"ろく", m:"altı (6)"},
  {w:"廊下", kana:"ろうか", m:"koridor"},
  {w:"私", kana:"わたし", m:"ben"},
  {w:"鰐", kana:"わに", m:"timsah"},
  // dakuten ile başlayanlar
  {w:"学校", kana:"がっこう", m:"okul"},
  {w:"外国", kana:"がいこく", m:"yabancı ülke"},
  {w:"銀行", kana:"ぎんこう", m:"banka"},
  {w:"牛乳", kana:"ぎゅうにゅう", m:"süt"},
  {w:"具合", kana:"ぐあい", m:"durum, hal (sağlık)"},
  {w:"月曜日", kana:"げつようび", m:"pazartesi"},
  {w:"元気", kana:"げんき", m:"sağlıklı, enerjik"},
  {w:"ご飯", kana:"ごはん", m:"pilav, yemek"},
  {w:"午後", kana:"ごご", m:"öğleden sonra"},
  {w:"雑誌", kana:"ざっし", m:"dergi"},
  {w:"時間", kana:"じかん", m:"zaman, saat"},
  {w:"自転車", kana:"じてんしゃ", m:"bisiklet"},
  {w:"じゃが芋", kana:"じゃがいも", m:"patates"},
  {w:"頭痛", kana:"ずつう", m:"baş ağrısı"},
  {w:"全部", kana:"ぜんぶ", m:"hepsi"},
  {w:"象", kana:"ぞう", m:"fil"},
  {w:"大学", kana:"だいがく", m:"üniversite"},
  {w:"電話", kana:"でんわ", m:"telefon"},
  {w:"電車", kana:"でんしゃ", m:"tren"},
  {w:"土曜日", kana:"どようび", m:"cumartesi"},
  {w:"動物", kana:"どうぶつ", m:"hayvan"},
  {w:"晩ご飯", kana:"ばんごはん", m:"akşam yemeği"},
  {w:"病院", kana:"びょういん", m:"hastane"},
  {w:"文化", kana:"ぶんか", m:"kültür"},
  {w:"勉強", kana:"べんきょう", m:"ders çalışma"},
  {w:"帽子", kana:"ぼうし", m:"şapka"},
  // --- Katakana ile başlayanlar (yabancı kökenli kelimeler) ---
  {w:"アイス", kana:"アイス", m:"dondurma"},
  {w:"アメリカ", kana:"アメリカ", m:"Amerika"},
  {w:"インターネット", kana:"インターネット", m:"internet"},
  {w:"ウール", kana:"ウール", m:"yün"},
  {w:"エレベーター", kana:"エレベーター", m:"asansör"},
  {w:"オレンジ", kana:"オレンジ", m:"portakal"},
  {w:"カメラ", kana:"カメラ", m:"fotoğraf makinesi"},
  {w:"カレー", kana:"カレー", m:"köri"},
  {w:"キロ", kana:"キロ", m:"kilo"},
  {w:"クラス", kana:"クラス", m:"sınıf"},
  {w:"クリスマス", kana:"クリスマス", m:"Noel"},
  {w:"ケーキ", kana:"ケーキ", m:"pasta, kek"},
  {w:"コーヒー", kana:"コーヒー", m:"kahve"},
  {w:"コンビニ", kana:"コンビニ", m:"bakkal, market"},
  {w:"サッカー", kana:"サッカー", m:"futbol"},
  {w:"シャツ", kana:"シャツ", m:"gömlek"},
  {w:"スープ", kana:"スープ", m:"çorba"},
  {w:"スポーツ", kana:"スポーツ", m:"spor"},
  {w:"セーター", kana:"セーター", m:"kazak"},
  {w:"ソファ", kana:"ソファ", m:"koltuk, kanepe"},
  {w:"タクシー", kana:"タクシー", m:"taksi"},
  {w:"チーズ", kana:"チーズ", m:"peynir"},
  {w:"チケット", kana:"チケット", m:"bilet"},
  {w:"ツアー", kana:"ツアー", m:"tur, gezi"},
  {w:"テレビ", kana:"テレビ", m:"televizyon"},
  {w:"テスト", kana:"テスト", m:"sınav, test"},
  {w:"トマト", kana:"トマト", m:"domates"},
  {w:"トイレ", kana:"トイレ", m:"tuvalet"},
  {w:"ナイフ", kana:"ナイフ", m:"bıçak"},
  {w:"ニュース", kana:"ニュース", m:"haber"},
  {w:"ヌードル", kana:"ヌードル", m:"erişte, noodle"},
  {w:"ネクタイ", kana:"ネクタイ", m:"kravat"},
  {w:"ノート", kana:"ノート", m:"defter"},
  {w:"ハンバーガー", kana:"ハンバーガー", m:"hamburger"},
  {w:"ヒーター", kana:"ヒーター", m:"ısıtıcı"},
  {w:"フォーク", kana:"フォーク", m:"çatal"},
  {w:"ヘリコプター", kana:"ヘリコプター", m:"helikopter"},
  {w:"ホテル", kana:"ホテル", m:"otel"},
  {w:"マスク", kana:"マスク", m:"maske"},
  {w:"ミルク", kana:"ミルク", m:"süt"},
  {w:"ムード", kana:"ムード", m:"hava, atmosfer"},
  {w:"メール", kana:"メール", m:"e-posta"},
  {w:"メニュー", kana:"メニュー", m:"menü"},
  {w:"モデル", kana:"モデル", m:"model"},
  {w:"ユーモア", kana:"ユーモア", m:"mizah"},
  {w:"ヨーグルト", kana:"ヨーグルト", m:"yoğurt"},
  {w:"ヨーロッパ", kana:"ヨーロッパ", m:"Avrupa"},
  {w:"ラーメン", kana:"ラーメン", m:"ramen"},
  {w:"ラジオ", kana:"ラジオ", m:"radyo"},
  {w:"リズム", kana:"リズム", m:"ritim"},
  {w:"ルール", kana:"ルール", m:"kural"},
  {w:"レストラン", kana:"レストラン", m:"restoran"},
  {w:"レモン", kana:"レモン", m:"limon"},
  {w:"ロボット", kana:"ロボット", m:"robot"},
  {w:"ワイン", kana:"ワイン", m:"şarap"},
  {w:"ガラス", kana:"ガラス", m:"cam"},
  {w:"ギター", kana:"ギター", m:"gitar"},
  {w:"グラス", kana:"グラス", m:"bardak"},
  {w:"ゲーム", kana:"ゲーム", m:"oyun"},
  {w:"ゴルフ", kana:"ゴルフ", m:"golf"},
  {w:"ジュース", kana:"ジュース", m:"meyve suyu"},
  {w:"ズボン", kana:"ズボン", m:"pantolon"},
  {w:"ゼロ", kana:"ゼロ", m:"sıfır"},
  {w:"ダンス", kana:"ダンス", m:"dans"},
  {w:"デパート", kana:"デパート", m:"büyük mağaza"},
  {w:"デザート", kana:"デザート", m:"tatlı"},
  {w:"ドア", kana:"ドア", m:"kapı"},
  {w:"ドラマ", kana:"ドラマ", m:"dizi"},
  {w:"バス", kana:"バス", m:"otobüs"},
  {w:"バナナ", kana:"バナナ", m:"muz"},
  {w:"ビール", kana:"ビール", m:"bira"},
  {w:"ビル", kana:"ビル", m:"bina"},
  {w:"ブーツ", kana:"ブーツ", m:"çizme"},
  {w:"ベッド", kana:"ベッド", m:"yatak"},
  {w:"ボール", kana:"ボール", m:"top"},
  {w:"パン", kana:"パン", m:"ekmek"},
  {w:"パソコン", kana:"パソコン", m:"bilgisayar"},
  {w:"ピアノ", kana:"ピアノ", m:"piyano"},
  {w:"ピザ", kana:"ピザ", m:"pizza"},
  {w:"プール", kana:"プール", m:"havuz"},
  {w:"プレゼント", kana:"プレゼント", m:"hediye"},
  {w:"ペン", kana:"ペン", m:"kalem"},
  {w:"ページ", kana:"ページ", m:"sayfa"},
  {w:"ポケット", kana:"ポケット", m:"cep"},
  {w:"ポスター", kana:"ポスター", m:"poster"},
];

// ---------- KANJİ (N5 seviyesi, ~100 adet) ----------
// c: karakter, on: on-yomi (katakana), kun: kun-yomi (hiragana),
// m: Türkçe anlam, ex: örnek kelime {w, r (kana), m}
export const KANJI = [
  // Sayılar
  {c:"一", on:["イチ"], kun:["ひと(つ)"], m:"bir", ex:{w:"一つ", r:"ひとつ", m:"bir tane"}},
  {c:"二", on:["ニ"], kun:["ふた(つ)"], m:"iki", ex:{w:"二人", r:"ふたり", m:"iki kişi"}},
  {c:"三", on:["サン"], kun:["みっ(つ)"], m:"üç", ex:{w:"三月", r:"さんがつ", m:"Mart"}},
  {c:"四", on:["シ"], kun:["よん","よ(つ)"], m:"dört", ex:{w:"四月", r:"しがつ", m:"Nisan"}},
  {c:"五", on:["ゴ"], kun:["いつ(つ)"], m:"beş", ex:{w:"五分", r:"ごふん", m:"beş dakika"}},
  {c:"六", on:["ロク"], kun:["むっ(つ)"], m:"altı", ex:{w:"六時", r:"ろくじ", m:"saat altı"}},
  {c:"七", on:["シチ"], kun:["なな(つ)"], m:"yedi", ex:{w:"七月", r:"しちがつ", m:"Temmuz"}},
  {c:"八", on:["ハチ"], kun:["やっ(つ)"], m:"sekiz", ex:{w:"八百", r:"はっぴゃく", m:"sekiz yüz"}},
  {c:"九", on:["キュウ","ク"], kun:["ここの(つ)"], m:"dokuz", ex:{w:"九時", r:"くじ", m:"saat dokuz"}},
  {c:"十", on:["ジュウ"], kun:["とお"], m:"on", ex:{w:"十日", r:"とおか", m:"ayın onu, on gün"}},
  {c:"百", on:["ヒャク"], kun:[], m:"yüz (100)", ex:{w:"三百", r:"さんびゃく", m:"üç yüz"}},
  {c:"千", on:["セン"], kun:["ち"], m:"bin", ex:{w:"三千", r:"さんぜん", m:"üç bin"}},
  {c:"万", on:["マン"], kun:[], m:"on bin", ex:{w:"一万円", r:"いちまんえん", m:"on bin yen"}},
  {c:"円", on:["エン"], kun:["まる(い)"], m:"yen; yuvarlak", ex:{w:"百円", r:"ひゃくえん", m:"yüz yen"}},
  // Zaman
  {c:"日", on:["ニチ","ジツ"], kun:["ひ","か"], m:"gün, güneş", ex:{w:"日曜日", r:"にちようび", m:"pazar günü"}},
  {c:"月", on:["ゲツ","ガツ"], kun:["つき"], m:"ay (gökteki ve takvim)", ex:{w:"月曜日", r:"げつようび", m:"pazartesi"}},
  {c:"火", on:["カ"], kun:["ひ"], m:"ateş", ex:{w:"火曜日", r:"かようび", m:"salı"}},
  {c:"水", on:["スイ"], kun:["みず"], m:"su", ex:{w:"水曜日", r:"すいようび", m:"çarşamba"}},
  {c:"木", on:["モク"], kun:["き"], m:"ağaç", ex:{w:"木曜日", r:"もくようび", m:"perşembe"}},
  {c:"金", on:["キン"], kun:["かね"], m:"altın; para", ex:{w:"お金", r:"おかね", m:"para"}},
  {c:"土", on:["ド"], kun:["つち"], m:"toprak", ex:{w:"土曜日", r:"どようび", m:"cumartesi"}},
  {c:"年", on:["ネン"], kun:["とし"], m:"yıl", ex:{w:"今年", r:"ことし", m:"bu yıl"}},
  {c:"時", on:["ジ"], kun:["とき"], m:"zaman, saat", ex:{w:"時間", r:"じかん", m:"zaman, süre"}},
  {c:"分", on:["フン","ブン"], kun:["わ(かる)"], m:"dakika; anlamak; bölmek", ex:{w:"五分", r:"ごふん", m:"beş dakika"}},
  {c:"半", on:["ハン"], kun:["なか(ば)"], m:"yarım", ex:{w:"六時半", r:"ろくじはん", m:"altı buçuk"}},
  {c:"今", on:["コン"], kun:["いま"], m:"şimdi", ex:{w:"今日", r:"きょう", m:"bugün"}},
  {c:"先", on:["セン"], kun:["さき"], m:"önce, ileri", ex:{w:"先生", r:"せんせい", m:"öğretmen"}},
  {c:"週", on:["シュウ"], kun:[], m:"hafta", ex:{w:"毎週", r:"まいしゅう", m:"her hafta"}},
  {c:"毎", on:["マイ"], kun:[], m:"her", ex:{w:"毎日", r:"まいにち", m:"her gün"}},
  {c:"何", on:["ナニ"], kun:["なに","なん"], m:"ne", ex:{w:"何時", r:"なんじ", m:"saat kaç"}},
  // İnsanlar
  {c:"人", on:["ジン","ニン"], kun:["ひと"], m:"insan, kişi", ex:{w:"日本人", r:"にほんじん", m:"Japon (kişi)"}},
  {c:"男", on:["ダン"], kun:["おとこ"], m:"erkek", ex:{w:"男の子", r:"おとこのこ", m:"erkek çocuk"}},
  {c:"女", on:["ジョ"], kun:["おんな"], m:"kadın", ex:{w:"女の人", r:"おんなのひと", m:"kadın (kişi)"}},
  {c:"子", on:["シ"], kun:["こ"], m:"çocuk", ex:{w:"子供", r:"こども", m:"çocuk"}},
  {c:"母", on:["ボ"], kun:["はは"], m:"anne", ex:{w:"お母さん", r:"おかあさん", m:"anne (saygılı)"}},
  {c:"父", on:["フ"], kun:["ちち"], m:"baba", ex:{w:"お父さん", r:"おとうさん", m:"baba (saygılı)"}},
  {c:"友", on:["ユウ"], kun:["とも"], m:"arkadaş", ex:{w:"友達", r:"ともだち", m:"arkadaş"}},
  {c:"名", on:["メイ"], kun:["な"], m:"isim", ex:{w:"名前", r:"なまえ", m:"isim"}},
  {c:"私", on:["シ"], kun:["わたし"], m:"ben; özel", ex:{w:"私たち", r:"わたしたち", m:"biz"}},
  {c:"生", on:["セイ"], kun:["い(きる)","う(まれる)"], m:"yaşam; doğmak; öğrenci", ex:{w:"学生", r:"がくせい", m:"öğrenci"}},
  // Vücut
  {c:"目", on:["モク"], kun:["め"], m:"göz", ex:{w:"目薬", r:"めぐすり", m:"göz damlası"}},
  {c:"口", on:["コウ"], kun:["くち"], m:"ağız", ex:{w:"入口", r:"いりぐち", m:"giriş (kapısı)"}},
  {c:"耳", on:["ジ"], kun:["みみ"], m:"kulak", ex:{w:"耳", r:"みみ", m:"kulak"}},
  {c:"手", on:["シュ"], kun:["て"], m:"el", ex:{w:"手紙", r:"てがみ", m:"mektup"}},
  {c:"足", on:["ソク"], kun:["あし"], m:"ayak, bacak", ex:{w:"足", r:"あし", m:"ayak"}},
  // Doğa
  {c:"山", on:["サン"], kun:["やま"], m:"dağ", ex:{w:"富士山", r:"ふじさん", m:"Fuji Dağı"}},
  {c:"川", on:["セン"], kun:["かわ"], m:"nehir", ex:{w:"川", r:"かわ", m:"nehir"}},
  {c:"田", on:["デン"], kun:["た"], m:"pirinç tarlası", ex:{w:"田中さん", r:"たなかさん", m:"Bay/Bayan Tanaka"}},
  {c:"空", on:["クウ"], kun:["そら"], m:"gökyüzü; boş", ex:{w:"空港", r:"くうこう", m:"havaalanı"}},
  {c:"天", on:["テン"], kun:["あま"], m:"gök, cennet", ex:{w:"天気", r:"てんき", m:"hava durumu"}},
  {c:"気", on:["キ"], kun:[], m:"enerji, ruh; hava", ex:{w:"元気", r:"げんき", m:"sağlıklı, enerjik"}},
  {c:"雨", on:["ウ"], kun:["あめ"], m:"yağmur", ex:{w:"大雨", r:"おおあめ", m:"şiddetli yağmur"}},
  {c:"花", on:["カ"], kun:["はな"], m:"çiçek", ex:{w:"花見", r:"はなみ", m:"çiçek izleme (hanami)"}},
  {c:"犬", on:["ケン"], kun:["いぬ"], m:"köpek", ex:{w:"子犬", r:"こいぬ", m:"yavru köpek"}},
  {c:"魚", on:["ギョ"], kun:["さかな"], m:"balık", ex:{w:"魚屋", r:"さかなや", m:"balıkçı (dükkânı)"}},
  // Yerler ve yönler
  {c:"電", on:["デン"], kun:[], m:"elektrik", ex:{w:"電車", r:"でんしゃ", m:"tren"}},
  {c:"車", on:["シャ"], kun:["くるま"], m:"araba, araç", ex:{w:"自転車", r:"じてんしゃ", m:"bisiklet"}},
  {c:"駅", on:["エキ"], kun:[], m:"istasyon", ex:{w:"駅前", r:"えきまえ", m:"istasyon önü"}},
  {c:"道", on:["ドウ"], kun:["みち"], m:"yol", ex:{w:"道", r:"みち", m:"yol"}},
  {c:"店", on:["テン"], kun:["みせ"], m:"dükkân", ex:{w:"喫茶店", r:"きっさてん", m:"kafe"}},
  {c:"家", on:["カ"], kun:["いえ","うち"], m:"ev", ex:{w:"家族", r:"かぞく", m:"aile"}},
  {c:"学", on:["ガク"], kun:["まな(ぶ)"], m:"öğrenmek", ex:{w:"大学", r:"だいがく", m:"üniversite"}},
  {c:"校", on:["コウ"], kun:[], m:"okul", ex:{w:"学校", r:"がっこう", m:"okul"}},
  {c:"国", on:["コク"], kun:["くに"], m:"ülke", ex:{w:"外国", r:"がいこく", m:"yabancı ülke"}},
  {c:"語", on:["ゴ"], kun:["かた(る)"], m:"dil, söz", ex:{w:"日本語", r:"にほんご", m:"Japonca"}},
  {c:"東", on:["トウ"], kun:["ひがし"], m:"doğu", ex:{w:"東京", r:"とうきょう", m:"Tokyo"}},
  {c:"西", on:["セイ","サイ"], kun:["にし"], m:"batı", ex:{w:"西口", r:"にしぐち", m:"batı çıkışı"}},
  {c:"南", on:["ナン"], kun:["みなみ"], m:"güney", ex:{w:"南口", r:"みなみぐち", m:"güney çıkışı"}},
  {c:"北", on:["ホク"], kun:["きた"], m:"kuzey", ex:{w:"北海道", r:"ほっかいどう", m:"Hokkaido"}},
  {c:"外", on:["ガイ"], kun:["そと"], m:"dış, dışarı", ex:{w:"外国人", r:"がいこくじん", m:"yabancı (kişi)"}},
  {c:"間", on:["カン"], kun:["あいだ"], m:"aralık, arası", ex:{w:"時間", r:"じかん", m:"zaman"}},
  {c:"上", on:["ジョウ"], kun:["うえ","のぼ(る)"], m:"üst, yukarı", ex:{w:"机の上", r:"つくえのうえ", m:"masanın üstü"}},
  {c:"下", on:["カ","ゲ"], kun:["した","くだ(る)"], m:"alt, aşağı", ex:{w:"地下鉄", r:"ちかてつ", m:"metro"}},
  {c:"左", on:["サ"], kun:["ひだり"], m:"sol", ex:{w:"左手", r:"ひだりて", m:"sol el"}},
  {c:"右", on:["ウ","ユウ"], kun:["みぎ"], m:"sağ", ex:{w:"右側", r:"みぎがわ", m:"sağ taraf"}},
  {c:"前", on:["ゼン"], kun:["まえ"], m:"ön, önce", ex:{w:"名前", r:"なまえ", m:"isim"}},
  {c:"後", on:["ゴ","コウ"], kun:["うし(ろ)","あと"], m:"arka, sonra", ex:{w:"午後", r:"ごご", m:"öğleden sonra"}},
  {c:"中", on:["チュウ"], kun:["なか"], m:"orta, içi", ex:{w:"中国", r:"ちゅうごく", m:"Çin"}},
  // Sıfatlar
  {c:"大", on:["ダイ","タイ"], kun:["おお(きい)"], m:"büyük", ex:{w:"大きい", r:"おおきい", m:"büyük"}},
  {c:"小", on:["ショウ"], kun:["ちい(さい)"], m:"küçük", ex:{w:"小さい", r:"ちいさい", m:"küçük"}},
  {c:"高", on:["コウ"], kun:["たか(い)"], m:"yüksek; pahalı", ex:{w:"高い", r:"たかい", m:"yüksek, pahalı"}},
  {c:"安", on:["アン"], kun:["やす(い)"], m:"ucuz; güvenli", ex:{w:"安い", r:"やすい", m:"ucuz"}},
  {c:"新", on:["シン"], kun:["あたら(しい)"], m:"yeni", ex:{w:"新聞", r:"しんぶん", m:"gazete"}},
  {c:"古", on:["コ"], kun:["ふる(い)"], m:"eski", ex:{w:"古い", r:"ふるい", m:"eski"}},
  {c:"長", on:["チョウ"], kun:["なが(い)"], m:"uzun", ex:{w:"長い", r:"ながい", m:"uzun"}},
  {c:"多", on:["タ"], kun:["おお(い)"], m:"çok", ex:{w:"多い", r:"おおい", m:"çok, fazla"}},
  {c:"少", on:["ショウ"], kun:["すく(ない)","すこ(し)"], m:"az", ex:{w:"少し", r:"すこし", m:"biraz"}},
  {c:"早", on:["ソウ"], kun:["はや(い)"], m:"erken", ex:{w:"早い", r:"はやい", m:"erken, hızlı"}},
  {c:"白", on:["ハク"], kun:["しろ(い)"], m:"beyaz", ex:{w:"白い", r:"しろい", m:"beyaz"}},
  // Fiiller
  {c:"食", on:["ショク"], kun:["た(べる)"], m:"yemek", ex:{w:"食べる", r:"たべる", m:"yemek (fiil)"}},
  {c:"飲", on:["イン"], kun:["の(む)"], m:"içmek", ex:{w:"飲む", r:"のむ", m:"içmek"}},
  {c:"見", on:["ケン"], kun:["み(る)"], m:"görmek, bakmak", ex:{w:"見る", r:"みる", m:"görmek, izlemek"}},
  {c:"聞", on:["ブン"], kun:["き(く)"], m:"duymak, dinlemek; sormak", ex:{w:"聞く", r:"きく", m:"dinlemek, sormak"}},
  {c:"読", on:["ドク"], kun:["よ(む)"], m:"okumak", ex:{w:"読む", r:"よむ", m:"okumak"}},
  {c:"書", on:["ショ"], kun:["か(く)"], m:"yazmak", ex:{w:"書く", r:"かく", m:"yazmak"}},
  {c:"話", on:["ワ"], kun:["はな(す)"], m:"konuşmak", ex:{w:"話す", r:"はなす", m:"konuşmak"}},
  {c:"買", on:["バイ"], kun:["か(う)"], m:"satın almak", ex:{w:"買い物", r:"かいもの", m:"alışveriş"}},
  {c:"行", on:["コウ"], kun:["い(く)"], m:"gitmek", ex:{w:"行く", r:"いく", m:"gitmek"}},
  {c:"来", on:["ライ"], kun:["く(る)"], m:"gelmek", ex:{w:"来る", r:"くる", m:"gelmek"}},
  {c:"出", on:["シュツ"], kun:["で(る)","だ(す)"], m:"çıkmak; çıkarmak", ex:{w:"出口", r:"でぐち", m:"çıkış (kapısı)"}},
  {c:"入", on:["ニュウ"], kun:["はい(る)","い(れる)"], m:"girmek; koymak", ex:{w:"入る", r:"はいる", m:"girmek"}},
  {c:"立", on:["リツ"], kun:["た(つ)"], m:"ayakta durmak", ex:{w:"立つ", r:"たつ", m:"ayağa kalkmak"}},
  {c:"休", on:["キュウ"], kun:["やす(む)"], m:"dinlenmek, tatil", ex:{w:"休み", r:"やすみ", m:"tatil, mola"}},
  {c:"会", on:["カイ"], kun:["あ(う)"], m:"buluşmak; toplantı", ex:{w:"会社", r:"かいしゃ", m:"şirket"}},
];

// ---------- OKUMA METİNLERİ ----------
// Her metin token listesi: t = görünen metin, r = hiragana okunuşu, m = Türkçe anlam
// r ve m olmayan tokenlar noktalama işaretidir (hover yok).
export const TEXTS = [
  {
    id: "jikoshoukai",
    title: "自己紹介 — Kendimi Tanıtayım",
    level: "Başlangıç",
    tokens: [
      {t:"私", r:"わたし", m:"ben"},
      {t:"は", r:"は", m:"edat: konu belirteci (wa okunur)"},
      {t:"アリ", r:"あり", m:"Ali (isim)"},
      {t:"です", r:"です", m:"-dır, -dir (kibar koşaç)"},
      {t:"。"},
      {t:"トルコ", r:"とるこ", m:"Türkiye"},
      {t:"から", r:"から", m:"edat: -den, -dan"},
      {t:"来ました", r:"きました", m:"geldim (gelmek fiilinin geçmiş kibar hali)"},
      {t:"。"},
      {t:"今", r:"いま", m:"şimdi"},
      {t:"、"},
      {t:"東京", r:"とうきょう", m:"Tokyo"},
      {t:"に", r:"に", m:"edat: -de, -da (yer/yön)"},
      {t:"住んでいます", r:"すんでいます", m:"yaşıyorum, oturuyorum"},
      {t:"。"},
      {t:"大学", r:"だいがく", m:"üniversite"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)"},
      {t:"日本語", r:"にほんご", m:"Japonca"},
      {t:"を", r:"を", m:"edat: nesne belirteci (o okunur)"},
      {t:"勉強しています", r:"べんきょうしています", m:"çalışıyorum (ders)"},
      {t:"。"},
      {t:"日本語", r:"にほんご", m:"Japonca"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"難しい", r:"むずかしい", m:"zor"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"が", r:"が", m:"bağlaç: ama, fakat"},
      {t:"、"},
      {t:"面白い", r:"おもしろい", m:"ilginç, eğlenceli"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"毎日", r:"まいにち", m:"her gün"},
      {t:"、"},
      {t:"新しい", r:"あたらしい", m:"yeni"},
      {t:"言葉", r:"ことば", m:"kelime"},
      {t:"を", r:"を", m:"edat: nesne belirteci"},
      {t:"覚えます", r:"おぼえます", m:"ezberliyorum, öğreniyorum"},
      {t:"。"},
      {t:"趣味", r:"しゅみ", m:"hobi"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"音楽", r:"おんがく", m:"müzik"},
      {t:"と", r:"と", m:"edat: ve, ile"},
      {t:"旅行", r:"りょこう", m:"seyahat"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"よろしくお願いします", r:"よろしくおねがいします", m:"memnun oldum (tanışma kalıbı)"},
      {t:"。"},
    ],
  },
  {
    id: "watashi-no-ichinichi",
    title: "私の一日 — Benim Günüm",
    level: "Başlangıç",
    tokens: [
      {t:"毎朝", r:"まいあさ", m:"her sabah"},
      {t:"、"},
      {t:"七時", r:"しちじ", m:"saat yedi"},
      {t:"に", r:"に", m:"edat: -de (zaman)"},
      {t:"起きます", r:"おきます", m:"kalkıyorum, uyanıyorum"},
      {t:"。"},
      {t:"朝ごはん", r:"あさごはん", m:"kahvaltı"},
      {t:"に", r:"に", m:"edat: -de, olarak"},
      {t:"パン", r:"ぱん", m:"ekmek"},
      {t:"を", r:"を", m:"edat: nesne belirteci"},
      {t:"食べて", r:"たべて", m:"yiyip (yemek fiilinin -te hali)"},
      {t:"、"},
      {t:"コーヒー", r:"こーひー", m:"kahve"},
      {t:"を", r:"を", m:"edat: nesne belirteci"},
      {t:"飲みます", r:"のみます", m:"içiyorum"},
      {t:"。"},
      {t:"八時", r:"はちじ", m:"saat sekiz"},
      {t:"に", r:"に", m:"edat: -de (zaman)"},
      {t:"家", r:"いえ", m:"ev"},
      {t:"を", r:"を", m:"edat: nesne belirteci"},
      {t:"出ます", r:"でます", m:"çıkıyorum"},
      {t:"。"},
      {t:"電車", r:"でんしゃ", m:"tren"},
      {t:"で", r:"で", m:"edat: ile (araç)"},
      {t:"学校", r:"がっこう", m:"okul"},
      {t:"へ", r:"へ", m:"edat: -e doğru (e okunur)"},
      {t:"行きます", r:"いきます", m:"gidiyorum"},
      {t:"。"},
      {t:"午前中", r:"ごぜんちゅう", m:"öğleden önce boyunca"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"授業", r:"じゅぎょう", m:"ders"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"あります", r:"あります", m:"var (cansız)"},
      {t:"。"},
      {t:"昼ごはん", r:"ひるごはん", m:"öğle yemeği"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"友達", r:"ともだち", m:"arkadaş"},
      {t:"と", r:"と", m:"edat: ile (birlikte)"},
      {t:"食堂", r:"しょくどう", m:"yemekhane"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)"},
      {t:"食べます", r:"たべます", m:"yiyorum"},
      {t:"。"},
      {t:"午後", r:"ごご", m:"öğleden sonra"},
      {t:"、"},
      {t:"図書館", r:"としょかん", m:"kütüphane"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)"},
      {t:"勉強します", r:"べんきょうします", m:"ders çalışıyorum"},
      {t:"。"},
      {t:"夕方", r:"ゆうがた", m:"akşamüstü"},
      {t:"、"},
      {t:"家", r:"いえ", m:"ev"},
      {t:"に", r:"に", m:"edat: -e (yön)"},
      {t:"帰ります", r:"かえります", m:"dönüyorum (eve)"},
      {t:"。"},
      {t:"夜", r:"よる", m:"gece"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"テレビ", r:"てれび", m:"televizyon"},
      {t:"を", r:"を", m:"edat: nesne belirteci"},
      {t:"見ます", r:"みます", m:"izliyorum"},
      {t:"。"},
      {t:"十一時", r:"じゅういちじ", m:"saat on bir"},
      {t:"に", r:"に", m:"edat: -de (zaman)"},
      {t:"寝ます", r:"ねます", m:"uyuyorum, yatıyorum"},
      {t:"。"},
    ],
  },
  {
    id: "nihon-no-shiki",
    title: "日本の四季 — Japonya'nın Dört Mevsimi",
    level: "Başlangıç+",
    tokens: [
      {t:"日本", r:"にほん", m:"Japonya"},
      {t:"に", r:"に", m:"edat: -de (yer)"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"四つ", r:"よっつ", m:"dört tane"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)"},
      {t:"季節", r:"きせつ", m:"mevsim"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"あります", r:"あります", m:"var (cansız)"},
      {t:"。"},
      {t:"春", r:"はる", m:"ilkbahar"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"暖かい", r:"あたたかい", m:"ılık, sıcak (hava)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"桜", r:"さくら", m:"kiraz çiçeği (sakura)"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"きれい", r:"きれい", m:"güzel, temiz"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"夏", r:"なつ", m:"yaz"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"暑い", r:"あつい", m:"sıcak (hava)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"海", r:"うみ", m:"deniz"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)"},
      {t:"泳ぎます", r:"およぎます", m:"yüzüyorum"},
      {t:"。"},
      {t:"秋", r:"あき", m:"sonbahar"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"涼しい", r:"すずしい", m:"serin"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"山", r:"やま", m:"dağ"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)"},
      {t:"木", r:"き", m:"ağaç"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"赤く", r:"あかく", m:"kırmızı (zarf hali)"},
      {t:"なります", r:"なります", m:"oluyor, dönüşüyor"},
      {t:"。"},
      {t:"冬", r:"ふゆ", m:"kış"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"寒い", r:"さむい", m:"soğuk (hava)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
      {t:"雪", r:"ゆき", m:"kar"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"降ります", r:"ふります", m:"yağıyor"},
      {t:"。"},
      {t:"私", r:"わたし", m:"ben"},
      {t:"は", r:"は", m:"edat: konu belirteci"},
      {t:"春", r:"はる", m:"ilkbahar"},
      {t:"が", r:"が", m:"edat: özne belirteci"},
      {t:"一番", r:"いちばん", m:"en (üstünlük derecesi)"},
      {t:"好き", r:"すき", m:"sevilen, hoşlanılan"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)"},
      {t:"。"},
    ],
  },
  {
    id: "neko-no-ichinichi",
    title: "猫の一日 — Kedinin Bir Günü",
    level: "Başlangıç",
    tokens: [
      {t:"うち", r:"うち", m:"bizim ev", me:"our home"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)", me:"particle: of (possessive)"},
      {t:"猫", r:"ねこ", m:"kedi", me:"cat"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"モモ", r:"もも", m:"Momo (kedi ismi)", me:"Momo (cat's name)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"モモ", r:"もも", m:"Momo (kedi ismi)", me:"Momo (cat's name)"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"朝ごはん", r:"あさごはん", m:"kahvaltı", me:"breakfast"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"食べて", r:"たべて", m:"yiyip (-te hali)", me:"eats and… (-te form)"},
      {t:"、"},
      {t:"窓", r:"まど", m:"pencere", me:"window"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)", me:"particle: of (possessive)"},
      {t:"外", r:"そと", m:"dışarısı", me:"outside"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"見ます", r:"みます", m:"bakıyor, izliyor", me:"looks at, watches"},
      {t:"。"},
      {t:"昼", r:"ひる", m:"öğlen, gündüz", me:"noon, daytime"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"長い", r:"ながい", m:"uzun", me:"long"},
      {t:"昼寝", r:"ひるね", m:"öğle uykusu", me:"nap"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"します", r:"します", m:"yapıyor", me:"does"},
      {t:"。"},
      {t:"夕方", r:"ゆうがた", m:"akşamüstü", me:"early evening"},
      {t:"、"},
      {t:"庭", r:"にわ", m:"bahçe", me:"garden"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)", me:"particle: at (place of action)"},
      {t:"鳥", r:"とり", m:"kuş", me:"bird"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"見ます", r:"みます", m:"izliyor", me:"watches"},
      {t:"。"},
      {t:"夜", r:"よる", m:"gece", me:"night"},
      {t:"、"},
      {t:"私", r:"わたし", m:"ben", me:"I"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)", me:"particle: of (possessive)"},
      {t:"ベッド", r:"べっど", m:"yatak", me:"bed"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)", me:"particle: at (place of action)"},
      {t:"寝ます", r:"ねます", m:"uyuyor", me:"sleeps"},
      {t:"。"},
      {t:"モモ", r:"もも", m:"Momo (kedi ismi)", me:"Momo (cat's name)"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)", me:"particle: of (possessive)"},
      {t:"一日", r:"いちにち", m:"bir gün", me:"a day"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"楽しい", r:"たのしい", m:"eğlenceli, keyifli", me:"fun, enjoyable"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
    ],
  },
  {
    id: "watashi-no-kazoku",
    title: "私の家族 — Ailem",
    level: "Başlangıç",
    tokens: [
      {t:"私", r:"わたし", m:"ben", me:"I"},
      {t:"の", r:"の", m:"edat: -nin (ilgi/aitlik)", me:"particle: of (possessive)"},
      {t:"家族", r:"かぞく", m:"aile", me:"family"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"四人", r:"よにん", m:"dört kişi", me:"four people"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"父", r:"ちち", m:"babam", me:"my father"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"先生", r:"せんせい", m:"öğretmen", me:"teacher"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"母", r:"はは", m:"annem", me:"my mother"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"病院", r:"びょういん", m:"hastane", me:"hospital"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)", me:"particle: at (place of action)"},
      {t:"働いています", r:"はたらいています", m:"çalışıyor", me:"works (is working)"},
      {t:"。"},
      {t:"妹", r:"いもうと", m:"kız kardeşim (küçük)", me:"my younger sister"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"高校生", r:"こうこうせい", m:"lise öğrencisi", me:"high school student"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"私たち", r:"わたしたち", m:"biz", me:"we"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"毎週", r:"まいしゅう", m:"her hafta", me:"every week"},
      {t:"日曜日", r:"にちようび", m:"pazar günü", me:"Sunday"},
      {t:"に", r:"に", m:"edat: -de (zaman)", me:"particle: on (time)"},
      {t:"公園", r:"こうえん", m:"park", me:"park"},
      {t:"へ", r:"へ", m:"edat: -e doğru (e okunur)", me:"particle: toward (read 'e')"},
      {t:"行きます", r:"いきます", m:"gidiyoruz", me:"we go"},
      {t:"。"},
      {t:"家族", r:"かぞく", m:"aile", me:"family"},
      {t:"と", r:"と", m:"edat: ile (birlikte)", me:"particle: with (together)"},
      {t:"話す", r:"はなす", m:"konuşmak", me:"to talk"},
      {t:"時間", r:"じかん", m:"zaman", me:"time"},
      {t:"が", r:"が", m:"edat: özne belirteci", me:"particle: subject marker"},
      {t:"大好き", r:"だいすき", m:"çok sevilen", me:"loved very much"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
    ],
  },
  {
    id: "resutoran-de",
    title: "レストランで — Restoranda",
    level: "Başlangıç+",
    tokens: [
      {t:"昨日", r:"きのう", m:"dün", me:"yesterday"},
      {t:"、"},
      {t:"友達", r:"ともだち", m:"arkadaş", me:"friend"},
      {t:"と", r:"と", m:"edat: ile (birlikte)", me:"particle: with (together)"},
      {t:"レストラン", r:"れすとらん", m:"restoran", me:"restaurant"},
      {t:"へ", r:"へ", m:"edat: -e doğru (e okunur)", me:"particle: toward (read 'e')"},
      {t:"行きました", r:"いきました", m:"gittim (geçmiş kibar)", me:"went (polite past)"},
      {t:"。"},
      {t:"私", r:"わたし", m:"ben", me:"I"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"ラーメン", r:"らーめん", m:"ramen", me:"ramen"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"注文しました", r:"ちゅうもんしました", m:"sipariş ettim", me:"ordered"},
      {t:"。"},
      {t:"友達", r:"ともだち", m:"arkadaş", me:"friend"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"寿司", r:"すし", m:"suşi", me:"sushi"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"食べました", r:"たべました", m:"yedi (geçmiş kibar)", me:"ate (polite past)"},
      {t:"。"},
      {t:"料理", r:"りょうり", m:"yemek(ler)", me:"food, dishes"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"とても", r:"とても", m:"çok", me:"very"},
      {t:"美味しかった", r:"おいしかった", m:"lezzetliydi (geçmiş)", me:"was delicious (past)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"少し", r:"すこし", m:"biraz", me:"a little"},
      {t:"高かった", r:"たかかった", m:"pahalıydı (geçmiş)", me:"was expensive (past)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"が", r:"が", m:"bağlaç: ama, fakat", me:"conjunction: but"},
      {t:"、"},
      {t:"楽しかった", r:"たのしかった", m:"eğlenceliydi (geçmiş)", me:"was fun (past)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"また", r:"また", m:"yine, tekrar", me:"again"},
      {t:"行きたい", r:"いきたい", m:"gitmek istiyorum", me:"want to go"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
    ],
  },
  {
    id: "kaimono",
    title: "買い物 — Alışveriş",
    level: "Başlangıç+",
    tokens: [
      {t:"今日", r:"きょう", m:"bugün", me:"today"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"デパート", r:"でぱーと", m:"büyük mağaza", me:"department store"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)", me:"particle: at (place of action)"},
      {t:"買い物", r:"かいもの", m:"alışveriş", me:"shopping"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"しました", r:"しました", m:"yaptım (geçmiş kibar)", me:"did (polite past)"},
      {t:"。"},
      {t:"新しい", r:"あたらしい", m:"yeni", me:"new"},
      {t:"靴", r:"くつ", m:"ayakkabı", me:"shoes"},
      {t:"と", r:"と", m:"edat: ve, ile", me:"particle: and, with"},
      {t:"白い", r:"しろい", m:"beyaz", me:"white"},
      {t:"シャツ", r:"しゃつ", m:"gömlek", me:"shirt"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"買いました", r:"かいました", m:"satın aldım", me:"bought"},
      {t:"。"},
      {t:"靴", r:"くつ", m:"ayakkabı", me:"shoes"},
      {t:"は", r:"は", m:"edat: konu belirteci", me:"particle: topic marker"},
      {t:"三千円", r:"さんぜんえん", m:"üç bin yen", me:"three thousand yen"},
      {t:"でした", r:"でした", m:"-idi (geçmiş kibar koşaç)", me:"was (polite past copula)"},
      {t:"。"},
      {t:"安かった", r:"やすかった", m:"ucuzdu (geçmiş)", me:"was cheap (past)"},
      {t:"です", r:"です", m:"-dır (kibar koşaç)", me:"is (polite copula)"},
      {t:"。"},
      {t:"それから", r:"それから", m:"ondan sonra", me:"after that"},
      {t:"、"},
      {t:"喫茶店", r:"きっさてん", m:"kafe", me:"café"},
      {t:"で", r:"で", m:"edat: -de (eylem yeri)", me:"particle: at (place of action)"},
      {t:"コーヒー", r:"こーひー", m:"kahve", me:"coffee"},
      {t:"を", r:"を", m:"edat: nesne belirteci", me:"particle: object marker"},
      {t:"飲みました", r:"のみました", m:"içtim (geçmiş kibar)", me:"drank (polite past)"},
      {t:"。"},
      {t:"いい", r:"いい", m:"iyi, güzel", me:"good, nice"},
      {t:"一日", r:"いちにち", m:"bir gün", me:"a day"},
      {t:"でした", r:"でした", m:"-idi (geçmiş kibar koşaç)", me:"was (polite past copula)"},
      {t:"。"},
    ],
  },
];
