// İngilizce içerik karşılıkları. UI metinleri lib/i18n.js'te; burada
// veri (kanji/kelime/okuma) çevirileri tutulur.

// Kanji karakteri → İngilizce anlam
export const KANJI_EN = {
  "一": "one", "二": "two", "三": "three", "四": "four", "五": "five",
  "六": "six", "七": "seven", "八": "eight", "九": "nine", "十": "ten",
  "百": "hundred", "千": "thousand", "万": "ten thousand", "円": "yen; circle",
  "日": "day; sun", "月": "month; moon", "火": "fire", "水": "water",
  "木": "tree", "金": "gold; money", "土": "earth, soil", "年": "year",
  "時": "time; hour", "分": "minute; to understand", "半": "half",
  "今": "now", "先": "before; ahead", "週": "week", "毎": "every",
  "何": "what", "人": "person", "男": "man", "女": "woman", "子": "child",
  "母": "mother", "父": "father", "友": "friend", "名": "name",
  "私": "I; private", "生": "life; to be born; student",
  "目": "eye", "口": "mouth", "耳": "ear", "手": "hand", "足": "foot; leg",
  "山": "mountain", "川": "river", "田": "rice field", "空": "sky; empty",
  "天": "heaven, sky", "気": "spirit, energy; air", "雨": "rain",
  "花": "flower", "犬": "dog", "魚": "fish",
  "電": "electricity", "車": "car, vehicle", "駅": "station",
  "道": "road, way", "店": "shop", "家": "house, home", "学": "to learn",
  "校": "school", "国": "country", "語": "language, word",
  "東": "east", "西": "west", "南": "south", "北": "north",
  "外": "outside", "間": "interval, between", "上": "up, above",
  "下": "down, below", "左": "left", "右": "right", "前": "front; before",
  "後": "behind; after", "中": "middle, inside",
  "大": "big", "小": "small", "高": "high; expensive", "安": "cheap; safe",
  "新": "new", "古": "old", "長": "long", "多": "many", "少": "few, little",
  "早": "early", "白": "white",
  "食": "to eat", "飲": "to drink", "見": "to see, look",
  "聞": "to hear, listen; ask", "読": "to read", "書": "to write",
  "話": "to speak", "買": "to buy", "行": "to go", "来": "to come",
  "出": "to exit; take out", "入": "to enter; put in", "立": "to stand",
  "休": "to rest; holiday", "会": "to meet; meeting",
};

// Kelime (w) → İngilizce anlam
export const WORDS_EN = {
  "朝": "morning", "雨": "rain", "秋": "autumn", "犬": "dog", "家": "house, home",
  "一": "one (number)", "海": "sea", "歌": "song", "駅": "station", "映画": "movie",
  "お茶": "tea", "お金": "money", "傘": "umbrella", "川": "river", "家族": "family",
  "木": "tree", "昨日": "yesterday", "北": "north", "今日": "today",
  "教室": "classroom", "靴": "shoes", "雲": "cloud", "今朝": "this morning",
  "結婚": "marriage", "子供": "child", "言葉": "word, language", "魚": "fish",
  "桜": "cherry blossom (sakura)", "新聞": "newspaper", "白": "white",
  "写真": "photograph", "宿題": "homework", "寿司": "sushi", "水曜日": "Wednesday",
  "先生": "teacher", "世界": "world", "空": "sky", "外": "outside",
  "卵": "egg", "食べ物": "food", "地図": "map", "父": "(my) father",
  "茶色": "brown", "月": "moon", "机": "desk", "手": "hand", "手紙": "letter",
  "鳥": "bird", "友達": "friend", "夏": "summer", "名前": "name", "肉": "meat",
  "庭": "garden", "布": "cloth, fabric", "沼": "swamp, pond", "猫": "cat",
  "値段": "price", "飲み物": "drink", "海苔": "seaweed (nori)", "花": "flower",
  "春": "spring", "人": "person", "昼": "noon, daytime", "百": "hundred",
  "冬": "winter", "船": "ship", "部屋": "room", "蛇": "snake", "本": "book",
  "星": "star", "窓": "window", "町": "town", "水": "water", "耳": "ear",
  "虫": "insect", "村": "village", "目": "eye", "眼鏡": "glasses",
  "森": "forest", "桃": "peach", "山": "mountain", "野菜": "vegetable",
  "雪": "snow", "夢": "dream", "夜": "night", "洋服": "clothes",
  "来年": "next year", "楽": "comfortable, easy", "林檎": "apple",
  "旅行": "travel", "留学": "study abroad", "留守": "away from home",
  "歴史": "history", "零": "zero", "六": "six (6)", "廊下": "corridor",
  "私": "I, me", "鰐": "crocodile",
  "学校": "school", "外国": "foreign country", "銀行": "bank",
  "牛乳": "milk", "具合": "condition (health)", "月曜日": "Monday",
  "元気": "healthy, energetic", "ご飯": "rice, meal", "午後": "afternoon",
  "雑誌": "magazine", "時間": "time, hour", "自転車": "bicycle",
  "じゃが芋": "potato", "頭痛": "headache", "全部": "everything",
  "象": "elephant", "大学": "university", "電話": "telephone",
  "電車": "train", "土曜日": "Saturday", "動物": "animal",
  "晩ご飯": "dinner", "病院": "hospital", "文化": "culture",
  "勉強": "studying", "帽子": "hat",
  "アイス": "ice cream", "アメリカ": "America", "インターネット": "internet",
  "ウール": "wool", "エレベーター": "elevator", "オレンジ": "orange",
  "カメラ": "camera", "カレー": "curry", "キロ": "kilo", "クラス": "class",
  "クリスマス": "Christmas", "ケーキ": "cake", "コーヒー": "coffee",
  "コンビニ": "convenience store", "サッカー": "football, soccer",
  "シャツ": "shirt", "スープ": "soup", "スポーツ": "sports",
  "セーター": "sweater", "ソファ": "sofa", "タクシー": "taxi",
  "チーズ": "cheese", "チケット": "ticket", "ツアー": "tour",
  "テレビ": "television", "テスト": "test, exam", "トマト": "tomato",
  "トイレ": "toilet", "ナイフ": "knife", "ニュース": "news",
  "ヌードル": "noodles", "ネクタイ": "necktie", "ノート": "notebook",
  "ハンバーガー": "hamburger", "ヒーター": "heater", "フォーク": "fork",
  "ヘリコプター": "helicopter", "ホテル": "hotel", "マスク": "mask",
  "ミルク": "milk", "ムード": "mood", "メール": "e-mail",
  "メニュー": "menu", "モデル": "model", "ユーモア": "humor",
  "ヨーグルト": "yogurt", "ヨーロッパ": "Europe", "ラーメン": "ramen",
  "ラジオ": "radio", "リズム": "rhythm", "ルール": "rule",
  "レストラン": "restaurant", "レモン": "lemon", "ロボット": "robot",
  "ワイン": "wine", "ガラス": "glass (material)", "ギター": "guitar",
  "グラス": "drinking glass", "ゲーム": "game", "ゴルフ": "golf",
  "ジュース": "juice", "ズボン": "trousers", "ゼロ": "zero",
  "ダンス": "dance", "デパート": "department store", "デザート": "dessert",
  "ドア": "door", "ドラマ": "drama, series", "バス": "bus",
  "バナナ": "banana", "ビール": "beer", "ビル": "building",
  "ブーツ": "boots", "ベッド": "bed", "ボール": "ball", "パン": "bread",
  "パソコン": "computer", "ピアノ": "piano", "ピザ": "pizza",
  "プール": "pool", "プレゼント": "present, gift", "ペン": "pen",
  "ページ": "page", "ポケット": "pocket", "ポスター": "poster",
};

// Eski okuma metinlerindeki Türkçe açıklama → İngilizce açıklama.
// (Yeni metinlerin tokenlarında `me` alanı zaten var.)
export const GLOSS_EN = {
  "ben": "I",
  "edat: konu belirteci (wa okunur)": "particle: topic marker (read 'wa')",
  "Ali (isim)": "Ali (a name)",
  "-dır, -dir (kibar koşaç)": "is (polite copula)",
  "Türkiye": "Turkey",
  "edat: -den, -dan": "particle: from",
  "geldim (gelmek fiilinin geçmiş kibar hali)": "came (polite past of 'to come')",
  "şimdi": "now",
  "Tokyo": "Tokyo",
  "edat: -de, -da (yer/yön)": "particle: in/at (place/direction)",
  "yaşıyorum, oturuyorum": "I live (am living)",
  "üniversite": "university",
  "edat: -de (eylem yeri)": "particle: at (place of action)",
  "Japonca": "Japanese (language)",
  "edat: nesne belirteci (o okunur)": "particle: object marker (read 'o')",
  "çalışıyorum (ders)": "am studying",
  "edat: konu belirteci": "particle: topic marker",
  "zor": "difficult",
  "-dır (kibar koşaç)": "is (polite copula)",
  "bağlaç: ama, fakat": "conjunction: but",
  "ilginç, eğlenceli": "interesting, fun",
  "her gün": "every day",
  "yeni": "new",
  "kelime": "word",
  "edat: nesne belirteci": "particle: object marker",
  "ezberliyorum, öğreniyorum": "I memorize, learn",
  "hobi": "hobby",
  "müzik": "music",
  "edat: ve, ile": "particle: and, with",
  "seyahat": "travel",
  "memnun oldum (tanışma kalıbı)": "nice to meet you (set phrase)",
  "her sabah": "every morning",
  "saat yedi": "seven o'clock",
  "edat: -de (zaman)": "particle: at (time)",
  "kalkıyorum, uyanıyorum": "I get up, wake up",
  "kahvaltı": "breakfast",
  "edat: -de, olarak": "particle: for, as",
  "ekmek": "bread",
  "yiyip (yemek fiilinin -te hali)": "eat and… (-te form of 'to eat')",
  "kahve": "coffee",
  "içiyorum": "I drink",
  "saat sekiz": "eight o'clock",
  "ev": "house, home",
  "çıkıyorum": "I leave, go out",
  "tren": "train",
  "edat: ile (araç)": "particle: by (means of)",
  "okul": "school",
  "edat: -e doğru (e okunur)": "particle: toward (read 'e')",
  "gidiyorum": "I go",
  "öğleden önce boyunca": "during the morning",
  "ders": "class, lesson",
  "edat: özne belirteci": "particle: subject marker",
  "var (cansız)": "there is (inanimate)",
  "öğle yemeği": "lunch",
  "arkadaş": "friend",
  "edat: ile (birlikte)": "particle: with (together)",
  "yemekhane": "cafeteria",
  "yiyorum": "I eat",
  "öğleden sonra": "afternoon",
  "kütüphane": "library",
  "ders çalışıyorum": "I study",
  "akşamüstü": "early evening",
  "edat: -e (yön)": "particle: to (direction)",
  "dönüyorum (eve)": "I return (home)",
  "gece": "night",
  "televizyon": "TV",
  "izliyorum": "I watch",
  "saat on bir": "eleven o'clock",
  "uyuyorum, yatıyorum": "I sleep, go to bed",
  "Japonya": "Japan",
  "edat: -de (yer)": "particle: in (place)",
  "dört tane": "four (things)",
  "edat: -nin (ilgi/aitlik)": "particle: of (possessive)",
  "mevsim": "season",
  "ilkbahar": "spring",
  "ılık, sıcak (hava)": "warm (weather)",
  "kiraz çiçeği (sakura)": "cherry blossom (sakura)",
  "güzel, temiz": "pretty, clean",
  "yaz": "summer",
  "sıcak (hava)": "hot (weather)",
  "deniz": "sea",
  "yüzüyorum": "I swim",
  "sonbahar": "autumn",
  "serin": "cool",
  "dağ": "mountain",
  "ağaç": "tree",
  "kırmızı (zarf hali)": "red (adverbial form)",
  "oluyor, dönüşüyor": "become, turn into",
  "kış": "winter",
  "soğuk (hava)": "cold (weather)",
  "kar": "snow",
  "yağıyor": "falls (rain/snow)",
  "en (üstünlük derecesi)": "the most (superlative)",
  "sevilen, hoşlanılan": "liked, favorite",
};

// Okuma metni başlıklarının İngilizceleri
export const TEXT_TITLE_EN = {
  "jikoshoukai": "Introducing Myself",
  "watashi-no-ichinichi": "My Day",
  "nihon-no-shiki": "The Four Seasons of Japan",
  "neko-no-ichinichi": "A Cat's Day",
  "watashi-no-kazoku": "My Family",
  "resutoran-de": "At the Restaurant",
  "kaimono": "Shopping",
};

// Kana grup başlıkları
export const GROUP_EN = {
  "Temel Sesler (Gojūon)": "Basic Sounds (Gojūon)",
  "Dakuten ﾞ / Handakuten ﾟ (Yumuşak / Patlamalı Sesler)":
    "Dakuten ﾞ / Handakuten ﾟ (Voiced / Semi-voiced Sounds)",
  "Birleşik Sesler (Yōon)": "Combined Sounds (Yōon)",
};

// Seviye etiketleri
export const LEVEL_EN = {
  "Başlangıç": "Beginner",
  "Başlangıç+": "Beginner+",
  "Kolay": "Easy",
  "Orta": "Intermediate",
  "İleri": "Advanced",
};
